#!/usr/bin/perl -w

use strict;
use LWP::UserAgent;
use XML::LibXML;
use Flickr::API2;

my $parser = XML::LibXML->new;

my $key    = 'dc7d97740216c982afae566ce098e108';
my $secret = '7993c5c669d59d0d';
my $id     = '36853098@N06';

my $flickr = new Flickr::API2({'key'    => $key,
			       'secret' => $secret});

my $extras = "tags,views,description";
my @photos = $flickr->photos->search(extras   => $extras,
				     user_id  => $id, 
				     tags     => 'consumerism' , 
				     per_page => 5);

my %params = ( 'method'   => 'flickr.photos.getInfo',
	       'api_key'  => $key,
	       'format'   => 'rest',
	       'photo_id' => '13763646673');


 # Create a user agent object

my $ua = LWP::UserAgent->new;
$ua->agent("GettingMyMetadata/0.1 ");

my $image_file = '>photostream.xml';
open my($fh), $image_file;
binmode $fh;

my $stream = $parser->load_xml(string => '<stream/>');
my $root   = $stream->documentElement();

for my $photo (@photos) {
    print "Title is " . $photo->title . "\n";
    print "id is " . $photo->id . "\n";
    print $photo->views . "\n";
    print $photo->page_url . "\n\n";

    my $api = $photo->api;
    my $raw = ${$photo->api}{_raw};

    my $req = HTTP::Request->new(GET => &genUri($photo->id));

    # Pass request to the user agent and get a response back
    my $res = $ua->request($req);

    # Check the outcome of the response
    if ($res->is_success) {
	my $xml_string = $res->content;
	my $xres = 
	    $parser->load_xml(
		string => $xml_string
	    );
	my $element = $xres->documentElement();
	$root->appendChild($element);
    } else {
	print $res->status_line, "\n";
    }
}

$stream->toFH($fh);

sub genUri {
    $params{'photo_id'}=shift;

    my $baseuri = 'https://api.flickr.com/services/rest/';
    my @pars    = ();

    while (my ($k,$v) = each %params) {
	push @pars,join('=',$k,$v);
    }
    return join '?',$baseuri,join('&',@pars);
}
