<?xml version='1.0' encoding="ISO-8859-1" ?>
<!DOCTYPE xsl:transform SYSTEM 'http://www.w3.org/People/cmsmcq/1999/xslt10.dtd'
[
<!ENTITY mdash  "\(em" >
<!ENTITY ndash  "\(en" >
<!ENTITY rsquo "'">
<!ENTITY lsquo "`">
<!ENTITY rdquo "\(rq">
<!ENTITY ldquo "\(rq">
<!ENTITY approx "\(~~">
<!ENTITY sp " ">
<!ENTITY nl "

">
]>
<xsl:transform  xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

<!--
	Reformats a TEI.2 document to troff
	$Id$
-->

        <xsl:output omit-xml-declaration="yes"
		    method="text"
		    media-type="application/x-troff-ms"
		    indent = "no"
		    encoding="ISO-8859-1" 	
		    />

<xsl:strip-space elements = "*" /> 

<xsl:template match="/" >
<xsl:text>
.de endnotes
.SH
Referenser
..
</xsl:text>
<xsl:apply-templates select="TEI.2" />
<xsl:text>
.endnotes
</xsl:text>
</xsl:template>

<xsl:template match="TEI.2" ><xsl:text disable-output-escaping="yes" >
.\" This is autogenerated using XSLT. Do not edit!
</xsl:text>
<xsl:apply-templates />
</xsl:template>

<xsl:template match="teiHeader" />

<xsl:template match="text" >
<xsl:apply-templates />
</xsl:template>

<xsl:template match="front" >
.ds RCSID <xsl:value-of select="/TEI.2/teiHeader/revisionDesc/change/@id" />
<xsl:apply-templates select="titlePage"/>
<xsl:if test="div[@type='abstract']">
.AB
<xsl:for-each select="div[@type='abstract']/p">
.small
<xsl:if test="position()&gt;1">
.sp 0.2v
</xsl:if>
<xsl:value-of select="." />
</xsl:for-each>
.AE
</xsl:if>
</xsl:template>

<xsl:template match="titlePage">
<xsl:if test="docTitle">
.TL
.hy 0
<xsl:for-each select="docTitle/titlePart">
<xsl:apply-templates/><xsl:text> </xsl:text>
</xsl:for-each>
.hy 1
</xsl:if>
<xsl:if test="byline">
<xsl:for-each select="byline/docAuthor">.AU
.display1
<xsl:apply-templates/>
.display2
</xsl:for-each>
</xsl:if>
</xsl:template>

<xsl:template match="body" >
<xsl:apply-templates />
</xsl:template>

<xsl:template match='div/head'>
.SH
<xsl:apply-templates />
</xsl:template>

<xsl:template match='div1[@type="acknowledgements"]'>
.LP
\f(BIAcknowledgments:\fR \(em
<xsl:value-of select='p' />
</xsl:template>

<xsl:template match='div[@type="display"]'>
.KF
<xsl:if test="@rend='box'">
.B1
</xsl:if>
.IP
<xsl:value-of select="head"/><xsl:text>
</xsl:text><xsl:apply-templates select="div" />
<xsl:if test="@rend='box'">
.sp 0.5
.B2
</xsl:if>
.sp
.KE
</xsl:template>

<xsl:template match='div1[@type="appendix"]'>
.bp
.SH
<xsl:apply-templates />
</xsl:template>

<xsl:template match='div1'>
.NH 1
<xsl:apply-templates />
</xsl:template>

<xsl:template match='div2'>
.NH 2
<xsl:apply-templates />
</xsl:template>

<xsl:template match='div3'>
.NH 3
<xsl:apply-templates />
</xsl:template>

<xsl:template match='div4'>
.NH 4
<xsl:apply-templates />
</xsl:template>

<xsl:template match='head'>
<xsl:apply-templates />
</xsl:template>

<xsl:template match='seg'><xsl:choose>
<xsl:when test="@rend='dropcap'">
.dropcap <xsl:apply-templates /> 3
</xsl:when>
<xsl:when test="@rend='smallcaps'">
.smallcaps
<xsl:apply-templates />
./smallcaps
</xsl:when>
<xsl:otherwise><xsl:apply-templates /></xsl:otherwise>
</xsl:choose>
</xsl:template>

<xsl:template match='p[figure]'>
    <xsl:apply-templates/>
</xsl:template>

<xsl:template match='sp/p'>
<xsl:text>
</xsl:text><xsl:apply-templates />
</xsl:template>

<xsl:template match='div/p'><xsl:text>
.IP
</xsl:text>
<xsl:apply-templates/>
</xsl:template>

<xsl:template match='p'>
<xsl:text disable-output-escaping="yes" >
.\" Matching paragraph
</xsl:text>
<xsl:choose>
<xsl:when test="@rend='noindent'">
.LP
<xsl:apply-templates /> 
</xsl:when>
<xsl:when test="@rend='box'">
.B1
.na
<xsl:apply-templates />
.ad
.B2
</xsl:when>
<xsl:when test="name(..)='quote'">
.IP
\fI<xsl:apply-templates />\fR
</xsl:when>
<xsl:otherwise>
.PP
<xsl:apply-templates /> 
</xsl:otherwise>
</xsl:choose>
</xsl:template>

<xsl:template match='q'>&ldquo;<xsl:apply-templates />&rdquo;</xsl:template>

<xsl:template match='soCalled'>&ldquo;<xsl:apply-templates />&rdquo;</xsl:template>

<!-- Lists -->
<xsl:template match='list'><xsl:text disable-output-escaping="yes" >
.\" bullet list
</xsl:text>
<xsl:apply-templates /> 
</xsl:template>

<xsl:template match='item'><xsl:text disable-output-escaping="yes" >
.\" A list item
.IP \fB\(sq\fP
</xsl:text>
<xsl:apply-templates /> 
</xsl:template>

<xsl:template match='opener'>
<xsl:apply-templates />
</xsl:template>

<xsl:template match='closer'>
<xsl:apply-templates />
</xsl:template>

<xsl:template match='address|dateline'><xsl:text>.ID 8.0c
</xsl:text><xsl:for-each select="addrLine|name|date">
<xsl:apply-templates/><xsl:text> </xsl:text>
</xsl:for-each>
.DE
</xsl:template>

<xsl:template match="salute|signed"><xsl:text>
.IP
</xsl:text><xsl:apply-templates/>&nl;
</xsl:template>

<xsl:template match="exemplum">
.KF
.B1
<xsl:apply-templates select='p'/>
<xsl:apply-templates select='eg'/>
.B2
.sp
.KE
</xsl:template>

<xsl:template match="eg">
.ID
.small
\f(CR<xsl:apply-templates />\fR
.DE
</xsl:template>

<xsl:template match='emph'>\fI<xsl:apply-templates />\fR</xsl:template>
<xsl:template match='hi'><xsl:choose>
<xsl:when test="@rend='kbd'">\f(CR<xsl:apply-templates />\fR</xsl:when>
<xsl:when test="@rend='bold'">\fB<xsl:apply-templates />\fR</xsl:when>
<xsl:when test="@rend='italics'">\fI<xsl:apply-templates />\fR</xsl:when>
<xsl:when test="@rend='bold-italics'">\f(BI<xsl:apply-templates />\f(BR</xsl:when>
</xsl:choose>
</xsl:template>

<xsl:template match='p/figure'>
<xsl:text disable-output-escaping="yes" >
.\" An eps image. This is a hack, since the perl script executing this
.\" Transformation has alreade changed .gif to .eps, so you better ensure
.\" That there is such an eps available
</xsl:text>
.KF
<xsl:choose>
<xsl:when test="contains(unparsed-entity-uri(@entity),'eps')">
.PSPIC <xsl:value-of select="unparsed-entity-uri(@entity)" /> 11.0c
</xsl:when>
<xsl:when test="contains(unparsed-entity-uri(@entity),'ms')">
.so <xsl:value-of select="unparsed-entity-uri(@entity)" />
</xsl:when>
</xsl:choose>
.fine-print
.IP<xsl:text disable-output-escaping="yes" >
.\"ll 8.0c
</xsl:text>
<xsl:choose>
<xsl:when test="/TEI.2/teiHeader/profileDesc/langUsage/language = 'swe'">
<xsl:text>Figur
</xsl:text>
</xsl:when>
<xsl:otherwise>
<xsl:text>Figure
</xsl:text>
</xsl:otherwise>
</xsl:choose>
<xsl:value-of select="@n" />.
<xsl:apply-templates select="./head" />
.sp 1.0c
.normal
.KE
</xsl:template>

<xsl:template match='note/p|note/xref'>[<xsl:value-of select="../@n"/>]
<xsl:text>
.am endnotes
.XP
</xsl:text>
[<xsl:value-of select="../@n"/>]
<xsl:apply-templates select="@to"/><xsl:text>
..
</xsl:text>
</xsl:template>

<xsl:template match='exemplum/p'>
.fine-print
.IP
<xsl:apply-templates />
.normal
</xsl:template>

<xsl:template match='note/bibl'>\**
.FS&nl;
.na&nl;
 <xsl:for-each select="author" >
   <xsl:choose>
     <xsl:when test="position()=1 and position()=last()">
       <xsl:value-of select="."/>:&nl;
     </xsl:when>
     <xsl:when test="position()=1 and not(position()=last())">
       <xsl:value-of select="."/>
     </xsl:when>
     <xsl:when test="position()>1 and not(position()=last())">;&nl;
       <xsl:value-of select="."/>
     </xsl:when>
     <xsl:when test="position()>1 and position()=last()">
       and&nl;<xsl:value-of select="."/>:&nl;
     </xsl:when>
  </xsl:choose>
 </xsl:for-each>    
  <xsl:apply-templates select="title" /> 
 <xsl:apply-templates select="edition" />
  <xsl:for-each select="editor" >
   <xsl:choose>
     <xsl:when test="position()=1 and position()=last()">&nl;
       <xsl:apply-templates/>&nl;(ed.)&nl;</xsl:when>
       <xsl:when test="position()=1 and not(position()=last())">&nl;
       <xsl:apply-templates/>
     </xsl:when>
     <xsl:when test="position()>1 and not(position()=last())">,&nl;
       <xsl:apply-templates/>
     </xsl:when>
     <xsl:when test="position()>1 and position()=last()">and&nl;
       <xsl:apply-templates/>&nl;(eds.)&nl;</xsl:when>
    </xsl:choose>
  </xsl:for-each>
  <xsl:apply-templates select="publisher" />
  <xsl:apply-templates select="imprint" />
 <xsl:apply-templates select="biblScope" />
 <xsl:apply-templates select="date" />
 <xsl:apply-templates select="title/xref/@to" mode="url" />.
.ad
.FE&nl;
</xsl:template>

<xsl:template match="p/title">
\fI<xsl:apply-templates/>\fR
<xsl:text>
</xsl:text>
<xsl:if test="xref/@to">
(cf., \f(CR<xsl:text disable-output-escaping="yes" >&lt;</xsl:text><xsl:value-of select="xref/@to"/><xsl:text disable-output-escaping="yes" >&gt;</xsl:text>\fR)
</xsl:if>
<xsl:text>
</xsl:text>
</xsl:template>

<xsl:template match="title">
\fI<xsl:apply-templates/>\fR,&sp;
</xsl:template>

<xsl:template match="date">
<xsl:apply-templates/>.
</xsl:template>

<xsl:template match="edition">
<xsl:apply-templates/>
</xsl:template>

<xsl:template match="xref">
<xsl:text>
.hy 0
.na
</xsl:text>
<xsl:apply-templates/><xsl:text>
.br
</xsl:text><xsl:value-of select="@to"/><xsl:text>
.ad
.hy 1</xsl:text>
</xsl:template>

<xsl:template match="title/xref/@to" mode="url" >
.hy 0
\f(CR<xsl:text disable-output-escaping="yes" >&lt;</xsl:text><xsl:value-of select="."/><xsl:text disable-output-escaping="yes" >&gt;</xsl:text>\fR.
.hy 1
</xsl:template>

<xsl:template match='sp'>
.XP
<xsl:for-each select="speaker|stage">
<xsl:choose>
<xsl:when test="name(.)='speaker'">
.smallcaps
<xsl:apply-templates /><xsl:if test="position() = last()">:</xsl:if>
./smallcaps
</xsl:when>
<xsl:when test="name(.)='stage'">
[\fI<xsl:apply-templates />\fR\/]<xsl:if test="position() = last()">:</xsl:if>
</xsl:when>
</xsl:choose>
</xsl:for-each>
<xsl:apply-templates select="p"/>
</xsl:template>

<xsl:template match="p/table"><xsl:text disable-output-escaping="yes" >
.\" We start a table here
</xsl:text>
.KF
.fine-print
.IP
<xsl:choose>
<xsl:when test="/TEI.2/teiHeader/profileDesc/langUsage/language = 'swe'">
<xsl:text>Tabell
</xsl:text>
</xsl:when>
<xsl:otherwise>
<xsl:text>Table
</xsl:text>
</xsl:otherwise>
</xsl:choose>
<xsl:value-of select="@n" />.
<xsl:apply-templates select="head" />
.normal
.TS
center box tab(;); 
<xsl:value-of select="@rend" /> .
<xsl:for-each select="row"><xsl:text>&nl;</xsl:text>
<xsl:for-each select="cell">T{
.na
.small
.hy 0
<xsl:if test="./@rend='bold'">.ft B
</xsl:if>
<xsl:apply-templates />
.hy 1
T}<xsl:if test="not(position()=last())">;</xsl:if>
</xsl:for-each>
<xsl:if test="not(position()=last())"><xsl:text>&nl;_&nl;</xsl:text></xsl:if></xsl:for-each>
.TE
.KE
</xsl:template>

<xsl:template match="table/head">
<xsl:apply-templates />
</xsl:template>

<xsl:template match="mdash">&mdash;</xsl:template>
<xsl:template match="ndash">&ndash;</xsl:template>
<xsl:template match="approx">&approx;</xsl:template>
<xsl:template match="greater-than">&gt;</xsl:template>
<xsl:template match="less-than">&lt;</xsl:template>



<!--


	$Log$
	Revision 1.1  2009/06/29 11:11:49  sigfrid
	Initial revision

	Revision 1.7  2003/08/28 08:16:49  sigge
	Lagt till C. M. Sperberg-McQueen DTD i doc-type-deklarationen.

	Revision 1.6  2003/02/19 20:15:19  sigge
	Fixat ett bättre system för noter.

	Revision 1.5  2002/11/05 19:23:21  siglun
	Corrected things. Improved support for smallcaps

	Revision 1.4  2002/08/20 12:08:50  siglun
	Fixed the exemplum tag

	Revision 1.3  2002/03/24 09:42:08  siglun
	moved stuff to tmac.bok, in order to make the translation more generic

	Revision 1.2  2002/02/03 21:38:49  siglun
	Fixat så att div2 tolkas som en centrerad asterisk, om det inte
	är den första sektionen i kapitlet.

	Revision 1.1  2001/11/20 20:47:35  siglun
	Initial revision


-->

</xsl:transform>


