<?xml version='1.0' encoding="ISO-8859-1" ?>
<xsl:transform  xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"
	        xmlns="http://www.w3.org/1999/xhtml">

<!--
	Reformats a HTML document to troff
	$Id$
-->

        <xsl:output method="text"
               media-type="application/x-troff-ms"
	       indent = "no"
               encoding="ISO-8859-1" 	
    />

<xsl:strip-space elements = "*" /> 
<xsl:preserve-space elements = "pre" /> 

<xsl:template match="/"><xsl:apply-templates select="html" /></xsl:template>

<xsl:template match="html" >.\" This is autogenerated from xhtml using
.\" XSLT. Do not edit!
.nr PI 2.5n
.nr PS 12
.nr VS 14
.de BT
.ie \\n[PN]==1 \{\
.       if d RCSID \{\
.               tl '''\\s-4\\*[RCSID]\\s+4'
.       \}
.\}
.el \{\
.       ie o .tl \\*[pg*OF]
.       el .tl  \\*[pg*OF]
.\}
..           
<xsl:apply-templates select="body" />
</xsl:template>

<xsl:template match='head'>
</xsl:template>

<xsl:template match="title" />

<xsl:template match='meta'>
.\" Matching meta
<xsl:choose>
<xsl:when test="contains(string(@name),'DC.creator')">
.EH "'%''\s-2<xsl:value-of select="@content" />\s+2'"
.ds AUTHOR  "<xsl:value-of select="@content" />
</xsl:when>
<xsl:when test="contains(string(@name),'DC.title')">
.OH "'\s-2\fI<xsl:value-of select="@content" />\fR\s+2''%'"
</xsl:when>
<xsl:when test="contains(string(@name),'RCSID')">
.ds RCSID "<xsl:value-of select="@content" />
</xsl:when>
</xsl:choose>
</xsl:template>

<!-- I had to define a few tags of my own. I'm particularly proud of
this one, which I regard a significant contribution -->

<xsl:template match='ignore'/>

<xsl:template match="body">
.\" Matching body
<xsl:apply-templates /> 
</xsl:template>

<xsl:template match='h1' >
.TL
<xsl:apply-templates /> 
.AU
\*[AUTHOR]
</xsl:template>

<xsl:template match='h2|h3|h4|h5|h6|h7'>
.SH
<xsl:apply-templates /> 
</xsl:template>

<xsl:template match='p'>
.\" Matching paragraph
<xsl:choose>
<xsl:when test="contains(string(@class),'author')">
.AU
<xsl:apply-templates /> 
</xsl:when>
<xsl:when test="contains(string(@class),'abstract')">
.AB
.ps 10
.vs 12
<xsl:apply-templates /> 
.AE
</xsl:when>
<xsl:otherwise>
.LP
<xsl:apply-templates /> 
</xsl:otherwise>
</xsl:choose>
</xsl:template>

<xsl:template match='dl'>
.\" definition list
<xsl:apply-templates /> 
</xsl:template>

<xsl:template match='dt'>
.XP
\fB<xsl:apply-templates />\fR
.br
</xsl:template>

<xsl:template match='dd'>
<xsl:apply-templates />
</xsl:template>


<xsl:template match='ul|ol'>
.\" A list is coming
<xsl:apply-templates /> 
</xsl:template>
<xsl:template match='li'>
.\" A list item
.IP \fB\s+3\(bu\s-3\fR
<xsl:apply-templates /> 
</xsl:template>

<xsl:template match='strong|b'>\fB<xsl:apply-templates />\fR</xsl:template>

<xsl:template match='a'>
<xsl:apply-templates />
</xsl:template>

<xsl:template match="table">
.\" We start a table here
.LP
.TS
<xsl:choose>
<xsl:when test="number(@border) &gt; 0">
box expand tab(;); 
<xsl:value-of select="@format" /> .
</xsl:when>
</xsl:choose>
<xsl:apply-templates />
.TE
</xsl:template>

<xsl:template match="tr">
<xsl:apply-templates />
_
</xsl:template>

<xsl:template match="br">
<xsl:apply-templates/>
.br
</xsl:template>

<!-- A table cell seperated from the next cell with a semi-colon -->
<xsl:template match="td">T{
.na
<xsl:apply-templates />
T};</xsl:template>

<!-- A table header cell seperated from the next cell with a semi-colon -->
<xsl:template match="th">T{
.na
\fB<xsl:apply-templates />\fR
T};</xsl:template>

<xsl:template match='pre'>
.\" A preformatted block, here represented by a block display
.LD
\f(CR<xsl:apply-templates />\fR
.DE
</xsl:template>

<xsl:template match='img'>
.\" An eps image. This is a hack, since the perl script executing this
.\" Transformation has alreade changed .gif to .eps, so you better ensure
.\" That there is such an eps available
.KF
.PSPIC <xsl:value-of select="@src" />
.IP
.ps 10
.vs 12
.\"ll 8.0c
\fI<xsl:apply-templates />\fP
.sp 1.0c
.KE
</xsl:template>

<!--

	$Log$
	Revision 1.1  2009/06/29 11:11:43  sigfrid
	Initial revision

	Revision 1.3  2002/01/18 16:40:58  siglun
	Fixed the font bug

	Revision 1.2  2001/05/04 16:40:49  siglun
	Fixed tables, page headers etc.

	Revision 1.1  2001/05/04 13:16:04  siglun
	Initial revision

-->

</xsl:transform>


